<?php
declare(strict_types=1);

namespace AppBundle\Utils\Aws;

use Aws\Sdk;

/**
 * Class AwsUtil
 * @package AppBundle\Utils\Aws
 * @author Plamen Markov <plamen@lynxlake.org>
 */
abstract class AwsUtil
{
    protected $sdk;

    public function __construct(Sdk $sdk)
    {
        $this->sdk = $sdk;
    }

    /**
     * @return string
     */
    public function generateUniqueFileName()
    {
        // md5() reduces the similarity of the file names generated by
        // uniqid(), which is based on timestamps
        return md5(uniqid());
    }
}