<?php
declare(strict_types=1);

namespace AppBundle\Repository;

use AppBundle\Entity\Client;
use Doctrine\ORM\EntityManagerInterface;
use Doctrine\ORM\Mapping\ClassMetadata;

/**
 * ClientRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ClientRepository extends \Doctrine\ORM\EntityRepository
{
    /** @var EntityManagerInterface $em */
    private $em;

    /**
     * CarRepository constructor.
     * @param EntityManagerInterface $em
     * @param ClassMetadata $class
     */
    public function __construct(EntityManagerInterface $em, ClassMetadata $class)
    {
        parent::__construct($em, $class);

        $this->em = $em;
    }

    /**
     * @param Client $client
     * @return Client
     */
    public function save(Client $client)
    {
        if (null === $client->getId()) {
            $this->em->persist($client);
        }
        $this->em->flush();

        return $client;
    }

    /**
     * @param Client $client
     */
    public function delete(Client $client)
    {
        $this->em->remove($client);
        $this->em->flush();
    }

    /**
     * @param string $keyword
     * @return Client[]|null
     */
    public function findByKeyword(string $keyword)
    {
        return $this->createQueryBuilder('c')
            ->where('c.idNumber LIKE :keyword')
            ->orWhere('c.firstName LIKE :keyword')
            ->orWhere('c.middleName LIKE :keyword')
            ->orWhere('c.lastName LIKE :keyword')
            ->setParameter('keyword', $keyword . '%')
            ->addOrderBy('c.firstName', 'ASC')
            ->addOrderBy('c.middleName', 'ASC')
            ->addOrderBy('c.lastName', 'ASC')
            ->getQuery()
            ->setFirstResult(0)
            ->setMaxResults(50)
            ->getResult();
    }
}
