<?php

namespace AppBundle\Repository;

/**
 * PolicyRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PolicyRepository extends \Doctrine\ORM\EntityRepository
{
}
