<?php
declare(strict_types=1);

namespace AppBundle\Repository;

/**
 * PolicyTypeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PolicyTypeRepository extends \Doctrine\ORM\EntityRepository
{
}
