<?php

namespace AppBundle\Repository;

/**
 * TypeOfCarRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TypeOfCarRepository extends \Doctrine\ORM\EntityRepository
{
}
