<?php
declare(strict_types=1);

namespace AppBundle\Repository;

/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     * @return mixed
     */
    public function findAllWithRoles()
    {
        return $this->createQueryBuilder('u')
            ->leftJoin('u.roles', 'r')
            ->select('u, r')
            ->orderBy('u.id', 'ASC')
            ->getQuery()
            ->setFirstResult(0)
            ->setMaxResults(100)
            ->getResult();
    }
}
