# Learn more about services, parameters and containers at
# https://symfony.com/doc/current/service_container.html
parameters:
    #parameter_name: value
    # AWS SDK
    aws_sdk:
        version: 'latest'
        region: '%aws_default_region%'
        credentials:
            key: '%aws_key%'
            secret: '%aws_secret%'

    pusher_options:
        cluster: '%pusher_cluster%'
        useTLS: true

services:
    # default configuration for services in *this* file
    _defaults:
        # automatically injects dependencies in your services
        autowire: true
        # automatically registers your services as commands, event subscribers, etc.
        autoconfigure: true
        # this means you cannot fetch services directly from the container via $container->get()
        # if you need to do this, you can override this setting on individual services
        public: false

    # makes classes in src/AppBundle available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    AppBundle\:
        resource: '../../src/AppBundle/*'
        # you can exclude directories or files
        # but if a service is unused, it's removed anyway
        exclude: '../../src/AppBundle/{Entity,Repository,Tests}'

    # controllers are imported separately to make sure they're public
    # and have a tag that allows actions to type-hint services
    AppBundle\Controller\:
        resource: '../../src/AppBundle/Controller'
        public: true
        tags: ['controller.service_arguments']

    AppBundle\Service\:
        resource: '../../src/AppBundle/Service'
        public: true

    # add more services, or override services that need manual wiring
    # AppBundle\Service\ExampleService:
    #     arguments:
    #         $someArgument: 'some_value'

    Aws\Sdk:
        arguments:
            - '%aws_sdk%'

    AppBundle\Service\Aws\AwsS3Util:
        arguments:
            - '@Aws\Sdk'
            - '%aws_bucket_name%'

    AppBundle\Service\Aws\UploadInterface: '@AppBundle\Service\Aws\AwsS3Util'

    AppBundle\Service\Pusher\RealTimeServiceInterface: '@AppBundle\Service\Pusher\PusherService'

    AppBundle\Service\TypeOfPolicy\TypeOfPolicyService:
        arguments:
            - "@=service('doctrine.orm.entity_manager').getRepository('AppBundle:TypeOfPolicy')"

    AppBundle\Service\Report\ReportService:
        arguments:
            - "@security.token_storage"
            - "@=service('doctrine.orm.entity_manager').getRepository('AppBundle:Payment')"

    AppBundle\Service\Policy\PolicyService:
        arguments:
            - "@security.token_storage"
            - "@=service('doctrine.orm.entity_manager').getRepository('AppBundle:Policy')"
            - "@=service('doctrine.orm.entity_manager').getRepository('AppBundle:TypeOfPolicy')"
            - "@=service('doctrine.orm.entity_manager').getRepository('AppBundle:GreenCard')"
            - "@=service('doctrine.orm.entity_manager').getRepository('AppBundle:Sticker')"
            - "@=service('doctrine.orm.entity_manager').getRepository('AppBundle:Bill')"
            - '@AppBundle\Service\Aws\UploadInterface'

    AppBundle\Service\Car\CarService:
        arguments:
            - "@security.token_storage"
            - "@=service('doctrine.orm.entity_manager').getRepository('AppBundle:Car')"
            - '@AppBundle\Service\Aws\UploadInterface'

    AppBundle\Service\Profile\ProfileService:
        arguments:
            - "@security.password_encoder"
            - "@security.token_storage"
            - "@=service('doctrine.orm.entity_manager').getRepository('AppBundle:User')"

    Pusher\Pusher:
        arguments:
            - '%pusher_key%'
            - '%pusher_secret%'
            - '%pusher_app_id%'
            - '%pusher_options%'

    AppBundle\Service\Pusher\PusherService:
        arguments:
            - '@Pusher\Pusher'
            - '%pusher_channel%'

    AppBundle\Service\Client\ClientService:
        arguments:
            - "@security.token_storage"
            - "@=service('doctrine.orm.entity_manager').getRepository('AppBundle:Client')"

    AppBundle\Service\Document\DocumentService:
        arguments:
            - "@=service('doctrine.orm.entity_manager').getRepository('AppBundle:Document')"
            - '@AppBundle\Service\Aws\UploadInterface'

    AppBundle\Service\Role\RoleService:
        arguments:
            - "@=service('doctrine.orm.entity_manager').getRepository('AppBundle:Role')"

    AppBundle\Service\Sticker\StickerService:
        arguments:
            - "@security.token_storage"
            - "@=service('doctrine.orm.entity_manager').getRepository('AppBundle:Sticker')"

    AppBundle\Service\Insurer\InsurerService:
        arguments:
            - "@security.token_storage"
            - "@=service('doctrine.orm.entity_manager').getRepository('AppBundle:Insurer')"

    AppBundle\Service\GreenCard\GreenCardService:
        arguments:
            - "@security.token_storage"
            - "@=service('doctrine.orm.entity_manager').getRepository('AppBundle:GreenCard')"

    AppBundle\Service\Bill\BillService:
        arguments:
            - "@security.token_storage"
            - "@=service('doctrine.orm.entity_manager').getRepository('AppBundle:Bill')"
